# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GetFeeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('content', models.CharField(default='', max_length=5000)),
                ('tags', models.CharField(default={}, max_length=200)),
                ('source', models.CharField(default='', max_length=50)),
                ('image', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
